import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 400px;
    height: 300px;

    callback open-file-dialog();

    VerticalBox {
        HorizontalBox {
            Button {
                text: @tr("Open");
                clicked => {
                    root.open-file-dialog();
                }
            }        
        }
        Rectangle {
            width: 100%;
            height: 80%;
            background: #f0f0f0;
        }
    }
}
